"""Deterministic cleanup for already-flattened (markdown / plain-text) content.

The right place to remove page boilerplate is main-content extraction on the
raw HTML (Readability / trafilatura), which is what the upstream poller does.
This module is imi's safety net for content that arrives already flattened to
markdown, where structural signals (DOM, link density per block) are gone and
only line-level rules remain. The rules come from the most frequent head/tail
lines in the production corpus (2026-09-26 audit), and are deliberately
conservative:

- only third-party sources are cleaned (``should_clean``): transcripts, own
  notes and other record-lane content pass through untouched;
- fenced code blocks are never modified;
- nav/share blocks are removed only at the head or tail of the document;
- an email footer is cut only in the last third of the text;
- if cleaning would leave almost nothing, the original is kept.

Pure functions; no I/O.
"""

from __future__ import annotations

import html
import re
from dataclasses import dataclass, field

# Sources whose content is third-party and safe to clean. Record-lane sources
# (manual notes, meeting bots, own tooling) are never rewritten, and neither
# are "document"/"other": they carry uploaded own documents and transcripts
# from recorders without a dedicated source. Mail is cleaned before admission
# decides its lane, so only mail-residue rules (URLs, HTML table debris) and
# page chrome apply to it.
CLEANABLE_SOURCES = frozenset({"web", "mail", "email", "rss", "youtube"})
# Residue rules for regex-stripped HTML mail only; on web markdown they would
# damage real links.
_MAIL_SOURCES = frozenset({"mail", "email"})

_IMAGE = re.compile(r"\[?!\[[^\]]*\]\([^)]*\)\]?(\([^)]*\))?")
_LINK = re.compile(r"\[([^\]]*)\]\([^)]*\)")
_FENCE = re.compile(r"^\s*(```|~~~)")

# Whole lines that are page chrome wherever they appear.
_CHROME_LINES = [
    r"\[?skip to (main )?content\]?(\(.*\))?",
    r"you signed in with another tab or window\..*",
    r"you signed out in another tab or window\..*",
    r"you switched accounts on another tab or window\..*",
    r"\{\{ message \}\}",
    r"there was an error while loading\..*",
    r"#+\s*uh oh!",
    r"-?\s*\[?notifications\]?(\(.*\))? you must be signed in to change notification settings",
    r"(share|subscribe|subscribesign in|sign in|sign up|log in|login|follow|copy link|mail|x\.com|facebook|linkedin|twitter|reddit|bluesky|threads|whatsapp|email)",
    r"-?\s*\[#\]\(.*\)",
    r"\\+\|?",
    r"(\*\s*){3,}",
    r"summaries were generated by google ai\. generative ai is experimental\.",
    r"#\s*\d+\s*min read",
    r"\d+\s*min read",
    r"labels:\s*.*",
    r"\(empty body\)",
]
_CHROME = re.compile(r"^\s*(?:" + "|".join(_CHROME_LINES) + r")\s*$", re.I)
# Empty rows and bare separator rows left when HTML mail tables are regex-
# stripped. Mail only: in markdown the separator row is what makes a table.
_MAIL_TABLE_DEBRIS = re.compile(r"^\s*(?:\|(\s*\|)+|(\|\s*-{3,}\s*)+\|)\s*$")

# An email footer starts at the first of these in the last third of the text.
_FOOTER_START = re.compile(
    r"^\s*(?:unsubscribe\b.*|.*\bto unsubscribe\b.*|you(?:'|’)re receiving this (?:email|message)\b.*|"
    r"you are receiving this (?:email|message)\b.*|manage (?:your )?(?:email )?(?:preferences|subscription).*|"
    r"update your (?:email )?preferences.*|this email was sent to\b.*|"
    r"please do not (?:respond|reply) to this e-?mail\b.*|powered by\s+stripe.*)\s*$",
    re.I,
)
# Newsletter preambles at the very top.
_HEAD_PREAMBLE = re.compile(
    r"^\s*(?:view (?:this (?:post|email) )?(?:on the web|in (?:your )?browser)\b.*|"
    r"forwarded this email\?.*|read (?:this|it) online\b.*)\s*$",
    re.I,
)
# HTML-to-text residue from regex-stripped mail: zero-width characters,
# undecoded entities, bare tracking URLs, "label (http://...)" link text.
_ZERO_WIDTH = re.compile("[\u200b\u200c\u200d\u2060\ufeff\u034f\u00ad]")
_BARE_URL_LINE = re.compile(r"^\s*<?https?://\S+>?\s*$")
_INLINE_URL = re.compile(r"(?<!\])\s*\(https?://[^)\s]+\)")  # never a markdown link target
_MIN_KEEP_RATIO = 0.10  # never cut a document to under 10% of its length...
_MIN_KEEP_CHARS = 200  # ...unless it is still at least this long


@dataclass
class CleanResult:
    text: str
    original_chars: int
    rules: dict[str, int] = field(default_factory=dict)

    @property
    def removed_chars(self) -> int:
        return self.original_chars - len(self.text)

    @property
    def changed(self) -> bool:
        return bool(self.rules)


def should_clean(source: str | None) -> bool:
    return (source or "").lower() in CLEANABLE_SOURCES


def _is_nav_line(line: str) -> bool:
    """A short line that is (almost) all links or empty-ish — a menu item.
    A heading is never a menu item: ``# [Title](url)`` is the document title."""
    if line.lstrip().startswith("#"):
        return False
    stripped = line.strip().lstrip("-*•> ").strip()
    if not stripped:
        return False
    links = _LINK.findall(stripped)
    if not links:
        return False
    text_without_links = _LINK.sub("", stripped).strip(" |·•-–—/")
    return len(text_without_links) <= 3 and len(stripped) < 200


def clean_content(text: str, source: str | None = None) -> CleanResult:
    """Clean third-party content; returns the original untouched for record
    sources or when the result would be implausibly short."""
    original = text or ""
    result = CleanResult(text=original, original_chars=len(original))
    if not should_clean(source) or not original.strip():
        return result

    rules: dict[str, int] = {}

    def hit(rule: str) -> None:
        rules[rule] = rules.get(rule, 0) + 1

    mail = (source or "").lower() in _MAIL_SOURCES
    lines = original.split("\n")
    kept: list[str] = []
    in_fence = False
    for line in lines:
        if _FENCE.match(line):
            in_fence = not in_fence
            kept.append(line)
            continue
        if in_fence:
            kept.append(line)
            continue
        new = line
        if "&" in new:
            decoded = html.unescape(new)
            if decoded != new:
                hit("html_entity")
                new = decoded
        stripped = _ZERO_WIDTH.sub("", new)
        if stripped != new:
            hit("zero_width")
            new = stripped
            if not new.strip():
                continue
        imaged = _IMAGE.sub("", new)
        if imaged != new:
            hit("image")
            new = imaged
            if not new.strip():
                continue
        if mail and _BARE_URL_LINE.match(new):
            hit("bare_url")
            continue
        if mail:
            unlinked = _INLINE_URL.sub("", new)
            if unlinked != new:
                hit("inline_url")
                new = unlinked
        if _CHROME.match(new):
            hit("chrome_line")
            continue
        if mail and _MAIL_TABLE_DEBRIS.match(new):
            hit("table_debris")
            continue
        kept.append(new)

    # Nav/menu blocks: only at the head and the tail of the document.
    def trim_edge(seq: list[str], rule: str) -> list[str]:
        i = 0
        while i < len(seq) and (not seq[i].strip() or _is_nav_line(seq[i]) or _HEAD_PREAMBLE.match(seq[i])):
            if seq[i].strip():
                hit(rule)
            i += 1
        return seq[i:]

    kept = trim_edge(kept, "nav_head")
    kept = list(reversed(trim_edge(list(reversed(kept)), "nav_tail")))

    # Email footer: cut from the first footer marker in the last third.
    if kept:
        start = int(len(kept) * 2 / 3)
        for idx in range(start, len(kept)):
            if _FOOTER_START.match(kept[idx]):
                hit("email_footer")
                kept = kept[:idx]
                break

    cleaned = "\n".join(line.rstrip() for line in kept)
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned).strip()

    too_short = len(cleaned) < _MIN_KEEP_CHARS and len(cleaned) < _MIN_KEEP_RATIO * len(original)
    if not rules or not cleaned or too_short:
        if rules and (not cleaned or too_short):
            result.rules = {"kept_original": 1}
        return result
    return CleanResult(text=cleaned, original_chars=len(original), rules=rules)
