#!/usr/bin/env python3
"""Build a Claude Code plugin from the repo's skills (ADR-005 §3).

The plugin bundles the core consumption skills (``skills/core/``) plus one
pack's skills. The repo is the only source of truth: the output directory is
generated, gitignored (``build/``), and never edited by hand.

    python scripts/build_plugin.py                                  # core skills only
    python scripts/build_plugin.py --pack freelance-implementation
    python scripts/build_plugin.py --pack freelance-implementation \\
        --mcp-url http://localhost:8080/api/mcp/sse                 # also declare the imi MCP server

Output (a local marketplace holding one plugin):

    build/plugins/imi-marketplace/
      .claude-plugin/marketplace.json
      imi/
        .claude-plugin/plugin.json
        skills/<skill>/SKILL.md ...
        .mcp.json                     # only with --mcp-url

Install it once in Claude Code:

    claude plugin marketplace add ./build/plugins/imi-marketplace
    claude plugin install imi@imi-local

or try it for one session: ``claude --plugin-dir build/plugins/imi-marketplace/imi``.
Skills are namespaced under the plugin name (``imi:brief``). Rebuild and run
``claude plugin marketplace update imi-local`` after pulling new skills.
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from pack_common import CORE_SKILLS_DIR, REPO_ROOT, load_pack, read_frontmatter  # noqa: E402

PLUGIN_NAME = "imi"
MARKETPLACE_NAME = "imi-local"
CORE_VERSION = "0.1.0"  # bump when skills/core changes in a user-visible way
DEFAULT_OUT = REPO_ROOT / "build" / "plugins"


def collect_skills(pack_ref: str | None) -> tuple[list[tuple[str, Path]], object | None]:
    skills: list[tuple[str, Path]] = []
    for d in sorted(p for p in CORE_SKILLS_DIR.iterdir() if (p / "SKILL.md").is_file()):
        skills.append(("core", d))
    pack = load_pack(pack_ref) if pack_ref else None
    if pack:
        for d in pack.skill_dirs():
            if not (d / "SKILL.md").is_file():
                raise SystemExit(f"{d}: missing SKILL.md (run scripts/validate_packs.py)")
            skills.append((pack.id, d))
    names: dict[str, str] = {}
    for origin, d in skills:
        meta, _ = read_frontmatter(d / "SKILL.md")
        name = (meta or {}).get("name") or d.name
        if name in names:
            raise SystemExit(f"skill name collision: {name!r} in {names[name]} and {origin}")
        names[name] = origin
    return skills, pack


def build(pack_ref: str | None, out: Path, mcp_url: str | None) -> Path:
    skills, pack = collect_skills(pack_ref)
    market = out / "imi-marketplace"
    if market.exists():
        shutil.rmtree(market)
    plugin = market / PLUGIN_NAME
    (plugin / ".claude-plugin").mkdir(parents=True)
    (market / ".claude-plugin").mkdir(parents=True)

    for _origin, d in skills:
        shutil.copytree(d, plugin / "skills" / d.name, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", ".DS_Store"))

    version = CORE_VERSION + (f"+{pack.id}.{pack.version}" if pack else "")
    what = f"core skills + the {pack.manifest.get('name', pack.id)} pack" if pack else "core skills"
    manifest = {
        "name": PLUGIN_NAME,
        "displayName": "imi",
        "version": version,
        "description": (
            f"imi consumption skills ({what}): briefs, constitution review, what-changed, memory wrap. "
            "Needs an imi MCP server connected as 'imi'. Generated by scripts/build_plugin.py — do not edit."
        ),
        "author": {"name": "imi contributors"},
        "license": "MIT",
        "keywords": ["imi", "knowledge-graph", "mcp", "memory"],
    }
    (plugin / ".claude-plugin" / "plugin.json").write_text(json.dumps(manifest, indent=2) + "\n")

    if mcp_url:
        transport = "http" if not mcp_url.rstrip("/").endswith("/sse") else "sse"
        (plugin / ".mcp.json").write_text(
            json.dumps({"mcpServers": {"imi": {"type": transport, "url": mcp_url}}}, indent=2) + "\n"
        )

    marketplace = {
        "name": MARKETPLACE_NAME,
        "owner": {"name": "imi contributors"},
        "description": "Locally generated imi skills plugin (scripts/build_plugin.py).",
        "plugins": [{"name": PLUGIN_NAME, "source": f"./{PLUGIN_NAME}", "description": manifest["description"]}],
    }
    (market / ".claude-plugin" / "marketplace.json").write_text(json.dumps(marketplace, indent=2) + "\n")
    return market


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pack", help="pack id whose skills to include alongside the core skills")
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT, help=f"output directory (default: {DEFAULT_OUT})")
    ap.add_argument("--mcp-url", help="declare the imi MCP server in the plugin (.mcp.json); omit if already configured")
    args = ap.parse_args(argv)

    market = build(args.pack, args.out, args.mcp_url)
    skills = sorted(p.name for p in (market / PLUGIN_NAME / "skills").iterdir())
    print(f"Built {market}")
    print(f"  skills: {', '.join(skills)}")
    print(f"  install: claude plugin marketplace add {market} && claude plugin install {PLUGIN_NAME}@{MARKETPLACE_NAME}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
