#!/usr/bin/env python3
"""Batch regeneration of attribution-grounded entity profiles (deferred Phase G).

PR #978 fixed *forward* profile generation: new meetings now produce
attribution-grounded profiles because EntityMeetingEnricher writes each
entity's "## Recent Signals" section (and typed relationships) BEFORE the
rich-profile prompt runs, and the prompt treats that block as the
authoritative source for who-did-what. But the existing corpus of profiles
was generated by the old path and still leaks co-participants' activities.

This script backfills those existing profiles WITHOUT re-running ingestion or
Claude entity extraction, by replaying the persisted corpus:

  Pass A (no Claude) — chronological signal enrichment
      For every meeting in chronological order, call the enricher's signal
      phase. This writes "## Recent Signals" onto each referenced entity file.
      The section is *replace-not-append*, so chronological order ensures each
      entity ends with its most-recent meeting's signals — exactly the live
      semantics.

  Pass B (Claude, once per entity) — grounded profile regeneration
      For every rich-profile-eligible entity (person/project/team), regenerate
      the profile once via DomainAwareEntityProcessor.update_entity_profile.
      _build_grounded_facts() reads the Recent Signals section written in
      Pass A, so the regenerated profile is attribution-grounded.

Usage (inside the container; scripts/ is not bind-mounted so docker cp first):
    docker cp scripts/regenerate_grounded_profiles.py main-dev:/app/scripts/
    docker exec -i main-dev python3 /app/scripts/regenerate_grounded_profiles.py --dry-run
    docker exec -i main-dev python3 /app/scripts/regenerate_grounded_profiles.py --limit 3
    docker exec -i main-dev python3 /app/scripts/regenerate_grounded_profiles.py --budget 5.0
    docker exec -i main-dev python3 /app/scripts/regenerate_grounded_profiles.py --entity-type person
"""

import argparse
import asyncio
import logging
import os
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, "/app")

import yaml

logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(name)s: %(message)s")
logger = logging.getLogger("regen_profiles")
# Quiet the very chatty enricher debug logs unless we want them.
logging.getLogger("app.services.entity_meeting_enricher").setLevel(logging.WARNING)

# Entity types that have rich XML profile prompts. Must intersect with the
# active domain's entity types (update_entity_profile raises on unknown types).
RICH_PROFILE_TYPES = {"person", "project", "team"}

# Rough per-profile cost estimate for budget gating. update_entity_profile does
# not surface token usage, so we gate on an estimate rather than actuals.
EST_COST_PER_PROFILE = 0.04


def parse_meeting_frontmatter(path: Path) -> dict | None:
    """Parse just the YAML frontmatter block from a meeting markdown file."""
    text = path.read_text(encoding="utf-8", errors="replace")
    if not text.startswith("---"):
        return None
    end = text.find("\n---", 3)
    if end == -1:
        return None
    block = text[3:end]
    try:
        fm = yaml.safe_load(block)
    except yaml.YAMLError as e:
        logger.warning("Frontmatter parse failed for %s: %s", path.name, e)
        return None
    return fm if isinstance(fm, dict) else None


def write_signal_section(path: str, section: str) -> None:
    """Replace or append the '## Recent Signals' section in a profile file.

    Writes DIRECTLY to the given path (the processor's people/ storage path),
    deliberately bypassing EntityService.save_entity_file — that helper
    redirects writes to a stale legacy entities/<type>/ twin when one exists,
    which would split Pass A's signals away from the people/ file Pass B reads.
    Mirrors the live enricher's _append_signal_section replace semantics.
    """
    import re

    with open(path, encoding="utf-8") as f:
        content = f.read()
    pattern = r"## Recent Signals\n.*?(?=\n## |\Z)"
    if re.search(pattern, content, re.DOTALL):
        updated = re.sub(pattern, section.strip(), content, flags=re.DOTALL)
    else:
        updated = content.rstrip() + "\n\n" + section
    with open(path, "w", encoding="utf-8") as f:
        f.write(updated)


def discover_meetings(repo_path: Path) -> list[dict]:
    """Return meetings sorted chronologically ascending.

    Each item: {bot_id, entities: {type: [names]}, sort_key}.
    Meetings missing a bot_id or entities_mentioned are skipped.
    """
    meetings: list[dict] = []
    meetings_dir = repo_path / "meetings"
    for md in sorted(meetings_dir.glob("meeting-*.md")):
        fm = parse_meeting_frontmatter(md)
        if not fm:
            continue
        bot_id = fm.get("bot_id") or fm.get("meeting_id")
        entities = fm.get("entities_mentioned") or {}
        if not bot_id or not isinstance(entities, dict):
            continue
        # Normalize: keep only type -> list[str] of non-empty names.
        clean: dict[str, list[str]] = {}
        for etype, names in entities.items():
            if not isinstance(names, list):
                continue
            vals = [n for n in names if isinstance(n, str) and n.strip()]
            if vals:
                clean[etype] = vals
        if not clean:
            continue
        sort_key = str(fm.get("updated_at") or fm.get("created_at") or md.name)
        meetings.append({"bot_id": bot_id, "entities": clean, "sort_key": sort_key})
    meetings.sort(key=lambda m: m["sort_key"])
    return meetings


async def main_async(args) -> int:
    from app.services.claude_client import get_claude_client
    from app.domain.entities.services import EntityService, get_entity_repository
    from app.services.entity_meeting_enricher import EntityMeetingEnricher
    from app.services.domain_aware_entity_processor import DomainAwareEntityProcessor
    from app.core.domain_config.domain_config_service import get_domain_config_service
    from app.git_ops import git_ops

    repo_path = Path(git_ops.repo_path)
    if not (repo_path / "meetings").exists():
        logger.error("No meetings/ dir under repo path %s", repo_path)
        return 1

    domain_config = get_domain_config_service().get_active_domain()
    if not domain_config:
        logger.error("No active domain config")
        return 1
    domain_types = set(domain_config.entities.keys())
    eligible_types = RICH_PROFILE_TYPES & domain_types
    if args.entity_type:
        eligible_types &= {args.entity_type}
    logger.info("Active domain: %s | eligible profile types: %s",
                domain_config.name, sorted(eligible_types))

    claude_client = get_claude_client()
    # The shared client hardcodes a 60s API timeout, which the largest entities
    # (many meetings -> big prompt) can exceed. Patch the underlying Anthropic
    # client for this run only via the SDK's with_options copy.
    if args.timeout and args.timeout != 60:
        try:
            claude_client.client = claude_client.client.with_options(timeout=float(args.timeout))
            logger.info("Patched Claude client timeout to %ss", args.timeout)
        except Exception as e:
            logger.warning("Could not patch client timeout: %s", e)
    entity_brain = EntityService(domain_id=getattr(domain_config, "domain_id", None)
                                 or "consulting_firm")
    if entity_brain._domain_loading_task:
        try:
            await entity_brain._domain_loading_task
        except Exception as e:
            logger.warning("Domain load issue: %s", e)
    entity_registry = get_entity_repository()
    enricher = EntityMeetingEnricher(entity_brain, entity_registry)
    processor = DomainAwareEntityProcessor(claude_client)

    meetings = discover_meetings(repo_path)
    logger.info("Discovered %d meetings with entity references", len(meetings))

    # Build the eligible-entity -> most-recent-meeting map (meetings are sorted
    # ascending, so the last write wins == most recent meeting).
    latest_meeting: dict[tuple[str, str], str] = {}
    for m in meetings:
        for etype, names in m["entities"].items():
            if etype not in eligible_types:
                continue
            for name in names:
                eid = entity_brain.normalize_entity_id(etype, name)
                latest_meeting[(etype, eid)] = m["bot_id"]

    if args.entity_id:
        latest_meeting = {
            k: v for k, v in latest_meeting.items() if k[1] == args.entity_id
        }

    # Scope to entities that ALREADY have a profile file. The meeting corpus
    # names ~2x more entities than exist on disk (first-name-only stubs,
    # misspellings, transient mentions). update_entity_profile writes
    # unconditionally, so without this filter Pass B would mint new ungrounded
    # files for noise — Pass A skips them anyway (no file to append signals to),
    # so they'd be the opposite of attribution-grounded. We only regenerate
    # real, existing profiles.
    existing: dict[tuple[str, str], str] = {}
    skipped_no_file = 0
    for (etype, eid), bot in latest_meeting.items():
        try:
            path = processor._get_entity_storage_path(etype, eid, domain_config)
        except ValueError:
            skipped_no_file += 1
            continue
        if os.path.exists(path):
            existing[(etype, eid)] = bot
        else:
            skipped_no_file += 1
    latest_meeting = existing

    targets = sorted(latest_meeting.items(), key=lambda kv: (kv[0][0], kv[0][1]))
    if args.limit:
        targets = targets[: args.limit]

    print("=" * 64)
    print("Grounded Profile Regeneration (Phase G backfill)")
    print("=" * 64)
    print(f"Repo: {repo_path}")
    print(f"Meetings to replay (Pass A): {len(meetings)}")
    print(f"Profiles to regenerate (Pass B): {len(targets)} "
          f"(skipped {skipped_no_file} named entities with no profile file)")
    print(f"Budget: ${args.budget:.2f}  (~${EST_COST_PER_PROFILE:.3f}/profile)")
    print(f"Mode: {'DRY RUN' if args.dry_run else 'LIVE'}")
    print("=" * 64)

    if args.dry_run:
        print("\n[DRY RUN] Pass A would enrich signals for these meetings (chrono):")
        for m in meetings[:5]:
            print(f"  - {m['bot_id']}  ({m['sort_key']})")
        if len(meetings) > 5:
            print(f"  ... and {len(meetings) - 5} more")
        print("\n[DRY RUN] Pass B would regenerate these profiles:")
        for (etype, eid), bot in targets:
            print(f"  - {etype:8s} {eid}  (trigger: meeting-{bot})")
        return 0

    # --- Pass A: chronological signal enrichment (no Claude) ----------------
    # Writes the "## Recent Signals" grounding section directly to each entity's
    # people/ file (the same path Pass B reads), matching signals to entities by
    # owner/entity-id exactly as the live enricher does. Chronological order +
    # replace-semantics means each entity ends with its most-recent meeting's
    # signals.
    from app.services.signal_store import signal_store

    print("\n--- Pass A: signal enrichment (chronological, direct to people/) ---")
    enriched_meetings = 0
    enriched_entities = 0
    for i, m in enumerate(meetings, 1):
        try:
            ms = signal_store.load(m["bot_id"])
        except Exception as e:
            logger.warning("signal load failed for %s: %s", m["bot_id"], e)
            ms = None
        if not ms or not getattr(ms, "signals", None):
            continue
        touched = 0
        for etype, names in m["entities"].items():
            if etype not in domain_types:
                continue
            for name in names:
                eid = entity_brain.normalize_entity_id(etype, name)
                try:
                    path = processor._get_entity_storage_path(etype, eid, domain_config)
                except ValueError:
                    continue
                if not os.path.exists(path):
                    continue
                matching = [
                    s for s in ms.signals
                    if any(getattr(r, "id", None) == eid for r in s.entities)
                    or (s.owner and getattr(s.owner, "id", None) == eid)
                ]
                if not matching:
                    continue
                section = enricher._build_signal_summary_section(matching, ms.meeting_title)
                try:
                    write_signal_section(path, section)
                    touched += 1
                    enriched_entities += 1
                except Exception as e:
                    logger.warning("signal write failed for %s: %s", eid, e)
        if touched:
            enriched_meetings += 1
        print(f"  [{i}/{len(meetings)}] {m['bot_id']}: {touched} entities enriched")
    print(f"Pass A complete: {enriched_meetings} meetings, "
          f"{enriched_entities} entity-signal writes")

    # --- Pass B: grounded profile regeneration (Claude, once per entity) ----
    print("\n--- Pass B: grounded profile regeneration ---")
    generated = 0
    failed = 0
    skipped_budget = 0
    spent = 0.0
    for i, ((etype, eid), bot) in enumerate(targets, 1):
        if spent + EST_COST_PER_PROFILE > args.budget:
            skipped_budget += 1
            print(f"  [{i}/{len(targets)}] SKIP {eid}: budget exhausted (${spent:.2f})")
            continue
        trigger = [f"meetings/meeting-{bot}.md"]
        try:
            await processor.update_entity_profile(
                entity_type=etype,
                entity_id=eid,
                trigger_files=trigger,
                domain_config=domain_config,
            )
            generated += 1
            spent += EST_COST_PER_PROFILE
            print(f"  [{i}/{len(targets)}] OK {etype} {eid}")
        except Exception as e:
            failed += 1
            logger.warning("Profile regen failed for %s %s: %s: %s",
                           etype, eid, type(e).__name__, e)
            print(f"  [{i}/{len(targets)}] FAIL {eid}: {type(e).__name__}")

    print("\n" + "=" * 64)
    print("Summary")
    print("=" * 64)
    print(f"Profiles regenerated: {generated}")
    print(f"Failed:               {failed}")
    print(f"Skipped (budget):     {skipped_budget}")
    print(f"Estimated spend:      ${spent:.2f}")

    # --- Commit (optional) ---------------------------------------------------
    if generated > 0 and not args.no_commit:
        try:
            # Stage ONLY the directories this script writes to — the domain-aware
            # layout writes profiles to people/, projects/, teams/ and Pass A
            # touches accounts/ (NOT entities/). Scoped (not `git add -A`) so any
            # unrelated working-tree changes — e.g. the bot-committed
            # constitution/staleness artifacts produced by rebuild_kb — are not
            # swept into this commit.
            for folder in ("people", "projects", "teams", "accounts"):
                folder_path = repo_path / folder
                if folder_path.exists():
                    subprocess.run(
                        ["git", "add", "--", folder], cwd=repo_path, check=True
                    )
            commit_msg = (
                "chore: backfill attribution-grounded entity profiles (Phase G)\n\n"
                f"Regenerated {generated} profiles via signal-grounded replay.\n"
                "Generated by: scripts/regenerate_grounded_profiles.py"
            )
            subprocess.run(["git", "commit", "-m", commit_msg], cwd=repo_path, check=True)
            print("\nCommitted regenerated profiles to repo git.")
        except subprocess.CalledProcessError as e:
            logger.warning("Git commit failed (changes left in working tree): %s", e)
    elif generated > 0:
        print("\n--no-commit: changes left uncommitted in repo working tree.")

    return 0 if failed == 0 else 1


def main():
    p = argparse.ArgumentParser(description=__doc__,
                                formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--dry-run", action="store_true",
                   help="Show the plan without enriching or calling Claude")
    p.add_argument("--budget", type=float, default=5.0,
                   help="Max estimated Claude spend in USD for Pass B (default 5.0)")
    p.add_argument("--entity-type", choices=sorted(RICH_PROFILE_TYPES),
                   help="Limit regeneration to one entity type")
    p.add_argument("--entity-id",
                   help="Regenerate a single entity (e.g. person-scott-jennings)")
    p.add_argument("--limit", type=int,
                   help="Cap number of profiles regenerated (validation runs)")
    p.add_argument("--no-commit", action="store_true",
                   help="Leave regenerated profiles uncommitted")
    p.add_argument("--timeout", type=float, default=60,
                   help="Override the Claude API timeout (s) for large entities")
    args = p.parse_args()
    sys.exit(asyncio.run(main_async(args)))


if __name__ == "__main__":
    main()
