"""
Models package - Complete backward compatibility.

All models from the original monolithic models.py are re-exported here.
"""

# Import shared types from central module first
from .agent import AgentObjective, IntelligencePattern, ObjectiveBoundaries, ObjectiveKPI

# Core API models
from .api import (
    BulkEnrichmentRequest,
    BulkEnrichmentResponse,
    BulkMergeOperation,
    BulkMergeResponse,
    BulkValidationRequest,
    BulkValidationResponse,
    CanonicalPerson,
    CanonicalProject,
    CanonicalTeam,
    ChatMessageRequest,
    DiffExplanationCache,
    DiffExplanationRequest,
    DiffExplanationResponse,
    DigestRequest,
    DigestResponse,
    DocumentMetadata,
    EnhancedDocumentMetadata,
    EnrichedEntity,
    EnrichedEntityRelationship,
    EnrichedEntityWithContext,
    EnrichmentOptions,
    EntityActivity,
    EntityAliasRequest,
    EntityAliasResponse,
    EntityArchiveResponse,
    EntityAutocompleteResponse,
    EntityDocumentsResponse,
    EntityExtraction,
    EntityInsight,
    EntityMergeRequest,
    EntityMergeResponse,
    EntityProfileResponse,
    EntitySearchResult,
    EntityStatistics,
    EntityUpdateRequest,
    EntityUpdateResponse,
    ExportRequest,
    ExportResponse,
    File,
    HealthResponse,
    ImportResponse,
    KnowledgeResponse,
    MetadataResponse,
    ModeSettings,
    ObjectiveExecution,
    ObjectivePerformanceReport,
    ObjectiveTemplate,
    PaginationInfo,
    PatternAnalysis,
    ProcessingResult,
    ProfileEntityRelationship,
    QueryRequest,
    QueryResponse,
    ReinitializeResponse,
    ToolExecution,
    UploadResponse,
    WorkflowExecution,
)
from .domain import DomainConfiguration, DomainEntityType
from .entity import (
    CanonicalEntity,
    EntityActivityResponse,
    EntityReference,
    EntitySearchResponse,
    EntitySuggestionRequest,
    EntitySuggestionResponse,
    OrganizationalContext,
    PersonProfile,
    SuggestedEntity,
)
from .github import GitHubCommit, GitHubPushEvent, GitHubRepository
from .meeting import MeetingState
from .tasks import TaskResponse, WebhookResponse
from .types import (
    CorrelationType,
    DomainEntityRelationship,
    EntityType,
    ExtractionPriority,
    MetricType,
    ObjectiveStatus,
    PatternTrigger,
    PatternType,
    ProcessingStatus,
    RelationshipType,
    SuccessMetric,
    TaskStatus,
)

__all__ = [
    "AgentObjective",
    "BulkEnrichmentRequest",
    "BulkEnrichmentResponse",
    "BulkMergeOperation",
    "BulkMergeResponse",
    "BulkValidationRequest",
    "BulkValidationResponse",
    "CanonicalEntity",
    "CanonicalPerson",
    "CanonicalProject",
    "CanonicalTeam",
    "ChatMessageRequest",
    "CorrelationType",
    "DiffExplanationCache",
    "DiffExplanationRequest",
    "DiffExplanationResponse",
    "DigestRequest",
    "DigestResponse",
    "DocumentMetadata",
    "DomainConfiguration",
    "DomainEntityRelationship",
    "DomainEntityType",
    "EnhancedDocumentMetadata",
    "EnrichedEntity",
    "EnrichedEntityRelationship",
    "EnrichedEntityWithContext",
    "EnrichmentOptions",
    "EntityActivity",
    "EntityActivityResponse",
    "EntityAliasRequest",
    "EntityAliasResponse",
    "EntityArchiveResponse",
    "EntityAutocompleteResponse",
    "EntityDocumentsResponse",
    "EntityExtraction",
    "EntityInsight",
    "EntityMergeRequest",
    "EntityMergeResponse",
    "EntityProfileResponse",
    "EntityReference",
    "EntitySearchResponse",
    "EntitySearchResult",
    "EntityStatistics",
    "EntitySuggestionRequest",
    "EntitySuggestionResponse",
    "EntityType",
    "EntityUpdateRequest",
    "EntityUpdateResponse",
    "ExportRequest",
    "ExportResponse",
    "ExtractionPriority",
    "File",
    "GitHubCommit",
    "GitHubPushEvent",
    "GitHubRepository",
    "HealthResponse",
    "ImportResponse",
    "IntelligencePattern",
    "KnowledgeResponse",
    "MeetingState",
    "MetadataResponse",
    "MetricType",
    "ModeSettings",
    "ObjectiveBoundaries",
    "ObjectiveExecution",
    "ObjectiveKPI",
    "ObjectivePerformanceReport",
    "ObjectiveStatus",
    "ObjectiveTemplate",
    "OrganizationalContext",
    "PaginationInfo",
    "PatternAnalysis",
    "PatternTrigger",
    "PatternType",
    "PersonProfile",
    "ProcessingResult",
    "ProcessingStatus",
    "ProfileEntityRelationship",
    "QueryRequest",
    "QueryResponse",
    "ReinitializeResponse",
    "RelationshipType",
    "SuccessMetric",
    "SuggestedEntity",
    "TaskResponse",
    "TaskStatus",
    "ToolExecution",
    "UploadResponse",
    "WebhookResponse",
    "WorkflowExecution",
]
# OrganizationalContext and SuggestedEntity are TYPE_CHECKING-only imports in
# api.core / api.entities: importing them there at module scope would recreate
# the entity <-> api.core import cycle. Every submodule is fully loaded by this
# point, and both names are bound above, so the forward refs resolve here.
from .api import core as _api_core
from .api import entities as _api_entities

for _model in (
    _api_core.EnrichedEntityWithContext,
    _api_core.EntityAutocompleteResponse,
    _api_entities.EnrichedEntityWithContext,
    _api_entities.EntityAutocompleteResponse,
):
    _model.model_rebuild()
